/**
 * Labeled aphasia turn dataset for scorer calibration.
 *
 * Each case is a realistic prompt/response pair drawn from typical
 * stroke-rehab discourse exercises (Free Talk, Finish-the-Thought),
 * with the clinically-expected scoring + adaptation.
 *
 * These labels represent what an SLP would say is the right call — they
 * are the "ground truth" the scorer + calibration are evaluated against.
 *
 * Used by `scripts/runScorerCalibration.ts`.
 */

import type {
  DiscourseErrorType,
  DiscourseAdaptationDirection,
  ScoreInput,
} from "@/lib/discourseSignalScorerCore";

export interface LabeledTurn {
  id: string;
  scenario: string;
  input: ScoreInput;
  expected: {
    errorType: DiscourseErrorType;
    adaptation: DiscourseAdaptationDirection;
    /** Was this turn a clinical "success" (composite > 0.6)? */
    success: boolean;
    /** Acceptable error types if the LLM picks a close-but-not-exact label. */
    acceptableErrorTypes?: DiscourseErrorType[];
  };
}

const t = (
  id: string,
  scenario: string,
  promptText: string,
  transcript: string,
  partial: Partial<ScoreInput>,
  expected: LabeledTurn["expected"],
): LabeledTurn => ({
  id,
  scenario,
  input: {
    exerciseSlug: "conversation_partner",
    promptText,
    transcript,
    wordCount: transcript ? transcript.trim().split(/\s+/).filter(Boolean).length : 0,
    latencyToFirstWordMs: 1800,
    durationMs: 4000,
    ...partial,
  },
  expected,
});

export const APHASIA_TURNS: LabeledTurn[] = [
  // ---------------------------------------------------------------------
  // FLUENT CORRECT — clean wins
  // ---------------------------------------------------------------------
  t("fc-01", "Direct on-topic answer",
    "What did you have for breakfast today?",
    "I had eggs and toast with coffee.",
    { topicKeywords: ["breakfast", "eggs", "toast", "coffee", "ate"] },
    { errorType: "fluent_correct", adaptation: "up", success: true },
  ),
  t("fc-02", "Short but complete answer",
    "Tell me about your weekend plans.",
    "I am visiting my daughter on Saturday.",
    { topicKeywords: ["weekend", "saturday", "sunday", "plans", "family"] },
    { errorType: "fluent_correct", adaptation: "up", success: true },
  ),
  t("fc-03", "Finish the thought, completed naturally",
    "When the rain started, I quickly...",
    "grabbed my umbrella and ran inside.",
    { exerciseSlug: "thought_continuation", topicKeywords: ["rain", "umbrella", "inside", "ran", "wet"] },
    { errorType: "fluent_correct", adaptation: "up", success: true },
  ),

  // ---------------------------------------------------------------------
  // OFF-TOPIC — fluent but irrelevant (the classic false-positive trap)
  // ---------------------------------------------------------------------
  t("ot-01", "Fluent ramble on wrong topic",
    "What did you have for breakfast today?",
    "The weather is really nice today and I might go for a walk later if my knee feels better.",
    { topicKeywords: ["breakfast", "eggs", "toast", "coffee", "ate"] },
    { errorType: "off_topic", adaptation: "down", success: false },
  ),
  t("ot-02", "Answers a different question",
    "Tell me about your weekend plans.",
    "My grandson called me yesterday about his school project.",
    { topicKeywords: ["weekend", "saturday", "plans"] },
    { errorType: "off_topic", adaptation: "down", success: false,
      acceptableErrorTypes: ["off_topic", "incomplete"] },
  ),
  t("ot-03", "Drifts away from the prompt",
    "When the rain started, I quickly...",
    "well you know my brother used to live in Florida years ago.",
    { exerciseSlug: "thought_continuation", topicKeywords: ["rain", "umbrella", "inside"] },
    { errorType: "off_topic", adaptation: "down", success: false },
  ),

  // ---------------------------------------------------------------------
  // CIRCUMLOCUTION — talking around the target
  // ---------------------------------------------------------------------
  t("cl-01", "Classic 'the thing' pattern",
    "What did you eat for breakfast?",
    "I had the thing, you know, the thing in the kitchen, with the bread.",
    { topicKeywords: ["breakfast", "eggs", "toast", "cereal", "ate"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] },
  ),
  t("cl-02", "Describes function instead of naming",
    "What animal lives in the ocean and has fins?",
    "the swimming one with the things on the side, you know, in the water.",
    { topicKeywords: ["fish", "shark", "whale", "ocean"] },
    { errorType: "circumlocution", adaptation: "down", success: false },
  ),

  // ---------------------------------------------------------------------
  // WORD FINDING — long latency, gaps, hesitation
  // ---------------------------------------------------------------------
  t("wf-01", "Long latency before partial answer",
    "What did you have for breakfast?",
    "um... the... uh... eggs.",
    { latencyToFirstWordMs: 9500, topicKeywords: ["breakfast", "eggs", "toast"] },
    { errorType: "word_finding", adaptation: "down", success: false,
      acceptableErrorTypes: ["word_finding", "incomplete"] },
  ),
  t("wf-02", "Gets there eventually with gaps",
    "Tell me about your weekend.",
    "I went to... uh... the... place... my daughter... visiting.",
    { latencyToFirstWordMs: 7500, topicKeywords: ["weekend", "daughter", "visit"] },
    { errorType: "word_finding", adaptation: "down", success: false,
      acceptableErrorTypes: ["word_finding", "incomplete", "circumlocution"] },
  ),

  // ---------------------------------------------------------------------
  // INCOMPLETE — trails off
  // ---------------------------------------------------------------------
  t("ic-01", "Trails off mid-sentence",
    "When the rain started, I quickly...",
    "I... uh... grabbed...",
    { exerciseSlug: "thought_continuation", topicKeywords: ["rain", "umbrella", "inside"] },
    { errorType: "incomplete", adaptation: "down", success: false,
      acceptableErrorTypes: ["incomplete", "word_finding"] },
  ),
  t("ic-02", "Single word answer to open-ended prompt",
    "Tell me about a happy memory from your childhood.",
    "fishing.",
    { topicKeywords: ["childhood", "memory", "happy"] },
    { errorType: "incomplete", adaptation: "down", success: false },
  ),

  // ---------------------------------------------------------------------
  // SEMANTIC PARAPHASIA — wrong but related word
  // ---------------------------------------------------------------------
  t("sp-01", "Substitutes related word",
    "What do you use to eat soup?",
    "I use a fork for the soup.",
    { topicKeywords: ["spoon", "soup", "eat"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia", "off_topic"] },
  ),

  // ---------------------------------------------------------------------
  // SURRENDER — explicit give-ups
  // ---------------------------------------------------------------------
  t("sr-01", "Direct surrender", "What did you have for breakfast?", "I don't know.",
    { topicKeywords: ["breakfast"] },
    { errorType: "surrender", adaptation: "down", success: false }),
  t("sr-02", "Skip request", "Tell me about your weekend.", "skip.",
    { topicKeywords: ["weekend"] },
    { errorType: "surrender", adaptation: "down", success: false }),
  t("sr-03", "Forgot phrasing", "Finish: when I get tired, I usually...", "I forgot.",
    { exerciseSlug: "thought_continuation", topicKeywords: ["tired", "rest", "sleep"] },
    { errorType: "surrender", adaptation: "down", success: false }),

  // ---------------------------------------------------------------------
  // NO RESPONSE
  // ---------------------------------------------------------------------
  t("nr-01", "Empty transcript", "What did you have for breakfast?", "",
    { topicKeywords: ["breakfast"], latencyToFirstWordMs: null, durationMs: 0 },
    { errorType: "no_response", adaptation: "down", success: false }),
  t("nr-02", "Filler only", "Tell me about your weekend.", "um uh hmm.",
    { topicKeywords: ["weekend"] },
    { errorType: "incomplete", adaptation: "down", success: false,
      acceptableErrorTypes: ["incomplete", "no_response"] }),

  // ---------------------------------------------------------------------
  // BORDERLINE — should HOLD, not adapt
  // ---------------------------------------------------------------------
  t("hd-01", "On topic but vague",
    "What did you do this morning?",
    "I did some stuff around the house.",
    { topicKeywords: ["morning", "house", "did"] },
    { errorType: "fluent_correct", adaptation: "hold", success: true,
      acceptableErrorTypes: ["fluent_correct", "incomplete"] }),
  t("hd-02", "Partial answer with mild hesitation",
    "Tell me about your favorite meal.",
    "I really like... pasta. With sauce. It's good.",
    { latencyToFirstWordMs: 3500, topicKeywords: ["meal", "food", "favorite", "like"] },
    { errorType: "fluent_correct", adaptation: "hold", success: true,
      acceptableErrorTypes: ["fluent_correct", "word_finding"] }),

  // ---------------------------------------------------------------------
  // STRONG SUCCESSES — should clearly trigger UP
  // ---------------------------------------------------------------------
  t("up-01", "Detailed structured answer",
    "Tell me about your morning routine.",
    "I wake up at seven, make coffee, read the newspaper, and then I take my medication before breakfast.",
    { topicKeywords: ["morning", "routine", "coffee", "breakfast"] },
    { errorType: "fluent_correct", adaptation: "up", success: true }),
  t("up-02", "Clear thought completion with detail",
    "When the rain started, I quickly...",
    "ran to the porch and closed all the windows so the floor wouldn't get wet.",
    { exerciseSlug: "thought_continuation", topicKeywords: ["rain", "windows", "inside", "wet"] },
    { errorType: "fluent_correct", adaptation: "up", success: true }),

  // ---------------------------------------------------------------------
  // UNCLEAR — garbled / ambiguous
  // ---------------------------------------------------------------------
  t("un-01", "Mostly unintelligible",
    "What did you have for breakfast?",
    "the and a was in for the.",
    { topicKeywords: ["breakfast"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "off_topic", "incomplete"] }),

  // =====================================================================
  // EXPANSION PACK v2 — weak-category enrichment (target: 20+ per category)
  //
  // Goal: provide enough labeled signal to detect movement when iterating
  // LLM prompts (v4+). Mix of exercise types, prompt categories, and
  // realistic stroke-survivor speech patterns drawn from clinical notes.
  // =====================================================================

  // ---------------------------------------------------------------------
  // CIRCUMLOCUTION — talking around the target (n=18 additional, total=20)
  // ---------------------------------------------------------------------
  t("cl-03", "Generic placeholder noun",
    "What do you write with?",
    "the thing, you know, the writing thing in your hand.",
    { topicKeywords: ["pen", "pencil", "write", "paper"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-04", "Describes appearance instead of name",
    "What do you call the yellow fruit monkeys eat?",
    "the long yellow one, you peel it, it's curved.",
    { topicKeywords: ["banana", "fruit", "yellow"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-05", "Describes function — utensil",
    "What do you cut bread with?",
    "the sharp one, in the drawer, you use it for cutting.",
    { topicKeywords: ["knife", "bread", "cut"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-06", "Describes role instead of person",
    "Who delivers your mail?",
    "the man that comes every day with the letters in the bag.",
    { topicKeywords: ["mail", "postman", "mailman", "carrier"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-07", "Describes location instead of naming",
    "Where do you go to buy groceries?",
    "the place where they have the food, with the carts and the lines.",
    { topicKeywords: ["store", "grocery", "supermarket", "market"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-08", "Talks around 'doctor'",
    "Who do you see when you are sick?",
    "the one in the white coat, with the stethoscope thing on his neck.",
    { topicKeywords: ["doctor", "physician", "sick", "hospital"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-09", "Tool circumlocution — hammer",
    "What do you use to put a nail in the wall?",
    "the heavy one, you hit with it, in the toolbox.",
    { topicKeywords: ["hammer", "nail", "tool"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-10", "Action circumlocution — driving",
    "How did you get to the appointment?",
    "I went in the thing, you know, the one with the wheels, sitting and going.",
    { topicKeywords: ["car", "drove", "driving", "vehicle"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-11", "Family member circumlocution",
    "Who came to visit you?",
    "the one, my, you know, the boy of my daughter, the little one.",
    { topicKeywords: ["grandson", "grandchild", "family", "visit"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-12", "Time circumlocution",
    "When does your therapy session start?",
    "after the lunch, before the dark, when the sun is high still.",
    { topicKeywords: ["afternoon", "time", "noon", "two"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-13", "Animal circumlocution",
    "What pet do you have at home?",
    "the small one with fur, four legs, it barks at people.",
    { topicKeywords: ["dog", "puppy", "pet"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-14", "Activity circumlocution",
    "What do you like to do in the evening?",
    "the watching thing, with the pictures and sound, in the living room.",
    { topicKeywords: ["television", "tv", "watch", "evening"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-15", "Body part circumlocution",
    "Where does it hurt?",
    "the top, you know, where the hair is, behind, near the back side.",
    { topicKeywords: ["head", "neck", "scalp", "back"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-16", "Clothing circumlocution",
    "What did you wear to the wedding?",
    "the long thing, the nice one, the dark blue with the buttons down.",
    { topicKeywords: ["suit", "dress", "jacket", "wore"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-17", "Multi-word target circumlocution",
    "What did you order at the restaurant?",
    "the round flat one with the red sauce and the cheese on top, you know.",
    { topicKeywords: ["pizza", "ordered", "food", "restaurant"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-18", "Thought continuation — circumlocutory finish",
    "When I want to read, I always reach for my...",
    "the thing on my face, the round ones with the wires over the ears.",
    { exerciseSlug: "thought_continuation",
      topicKeywords: ["glasses", "spectacles", "reading"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-19", "Verb circumlocution",
    "What do you do with a book?",
    "you do the eyes thing, you look at the words, page after page.",
    { topicKeywords: ["read", "reading", "book"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),
  t("cl-20", "Place circumlocution — bedroom",
    "Where do you sleep at night?",
    "the room with the bed, upstairs, where it's quiet and dark.",
    { topicKeywords: ["bedroom", "bed", "sleep", "night"] },
    { errorType: "circumlocution", adaptation: "down", success: false,
      acceptableErrorTypes: ["circumlocution", "word_finding"] }),

  // ---------------------------------------------------------------------
  // SEMANTIC PARAPHASIA — wrong but related (n=19 additional, total=20)
  // ---------------------------------------------------------------------
  t("sp-02", "Utensil swap — knife for fork",
    "What do you use to spear a piece of meat?",
    "I use the knife to pick up the meat from my plate.",
    { topicKeywords: ["fork", "meat", "eat"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-03", "Animal swap — dog for cat",
    "What animal says 'meow'?",
    "the dog says meow when it wants food.",
    { topicKeywords: ["cat", "kitten", "meow"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-04", "Color swap — related shade",
    "What color is the sky on a clear day?",
    "the sky is green when there are no clouds.",
    { topicKeywords: ["blue", "sky", "color"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-05", "Family swap — son for daughter",
    "Tell me about your daughter.",
    "my son lives nearby and he calls me every Sunday morning.",
    { topicKeywords: ["daughter", "family", "child"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia", "off_topic"] }),
  t("sp-06", "Day swap — Tuesday for Thursday",
    "What day is your therapy appointment?",
    "my appointment is on Tuesday at ten in the morning.",
    { topicKeywords: ["thursday", "appointment", "therapy"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-07", "Body part swap — arm for leg",
    "Which body part did you hurt?",
    "I hurt my arm when I fell down the stairs.",
    { topicKeywords: ["leg", "knee", "fell", "hurt"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-08", "Vehicle swap — bus for train",
    "How did you get to the city?",
    "I took the bus from the station, it took two hours.",
    { topicKeywords: ["train", "station", "city"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-09", "Fruit swap — apple for orange",
    "What fruit do you peel before eating?",
    "I always eat an apple after lunch, peel it first.",
    { topicKeywords: ["orange", "banana", "peel"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-10", "Time swap — morning for evening",
    "When do you watch the news?",
    "I watch the news in the morning before bed.",
    { topicKeywords: ["evening", "night", "news"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-11", "Drink swap — coffee for tea",
    "What hot drink do you have in the afternoon?",
    "I have coffee in the afternoon with a biscuit.",
    { topicKeywords: ["tea", "afternoon", "drink"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia", "fluent_correct"] }),
  t("sp-12", "Tool swap — screwdriver for hammer",
    "What do you use to drive a nail?",
    "I get the screwdriver from the toolbox to put the nail in.",
    { topicKeywords: ["hammer", "nail", "tool"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-13", "Clothing swap — shoes for socks",
    "What goes on your feet first in the morning?",
    "I put my shoes on first before my pants.",
    { topicKeywords: ["socks", "feet", "morning"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-14", "Furniture swap — chair for table",
    "What do you eat dinner on?",
    "we always eat at the chair in the dining room.",
    { topicKeywords: ["table", "dinner", "dining"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-15", "Verb swap — walk for run",
    "What did you do when you saw the bus leaving?",
    "I walked as fast as I could to catch it.",
    { topicKeywords: ["ran", "run", "bus", "hurry"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia", "fluent_correct"] }),
  t("sp-16", "Season swap — winter for summer",
    "What season has the longest days?",
    "winter has the longest days when the sun is up the most.",
    { topicKeywords: ["summer", "season", "sun", "long"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-17", "Weather swap — rain for snow",
    "What falls from the sky in winter?",
    "the rain comes down cold and white in the winter.",
    { topicKeywords: ["snow", "winter", "cold", "white"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-18", "Number swap",
    "How many days are in a week?",
    "there are five days in a week, Monday to Friday.",
    { topicKeywords: ["seven", "week", "days"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),
  t("sp-19", "Thought continuation — wrong but related noun",
    "I was thirsty so I poured myself a glass of...",
    "milk, nice and cold, from the fridge.",
    { exerciseSlug: "thought_continuation",
      topicKeywords: ["water", "juice", "drink", "thirsty"] },
    { errorType: "semantic_paraphasia", adaptation: "hold", success: false,
      acceptableErrorTypes: ["semantic_paraphasia", "fluent_correct"] }),
  t("sp-20", "Category swap — fish for bird",
    "What animal lays eggs and flies?",
    "the fish lay eggs and they swim around in the water.",
    { topicKeywords: ["bird", "chicken", "eggs", "fly"] },
    { errorType: "semantic_paraphasia", adaptation: "down", success: false,
      acceptableErrorTypes: ["semantic_paraphasia"] }),

  // ---------------------------------------------------------------------
  // UNCLEAR — garbled / ambiguous (n=19 additional, total=20)
  // ---------------------------------------------------------------------
  t("un-02", "Phonemic jargon",
    "Tell me what you did this morning.",
    "I gleeped the morthing and then sutted the rell.",
    { topicKeywords: ["morning", "did", "today"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear"] }),
  t("un-03", "Mixed real and nonsense words",
    "What did you eat for lunch?",
    "I had some flemp with the ranner on top, very good.",
    { topicKeywords: ["lunch", "ate", "food"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear"] }),
  t("un-04", "Sound substitutions throughout",
    "Tell me about your weekend.",
    "the wenkend was nife, I sat with the famly and ate the bisses.",
    { topicKeywords: ["weekend", "family"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "fluent_correct"] }),
  t("un-05", "Recurring stereotypy",
    "What is your favorite hobby?",
    "the do-do, do-do, the do-do thing, you know, do-do.",
    { topicKeywords: ["hobby", "favorite"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "no_response"] }),
  t("un-06", "Function words only with filler",
    "Tell me about your morning.",
    "the and the with for in the to and a was.",
    { topicKeywords: ["morning"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "incomplete"] }),
  t("un-07", "Neologistic word salad",
    "What did you do yesterday?",
    "I splanted the goober and frined with the kember in the parsh.",
    { topicKeywords: ["yesterday", "did"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear"] }),
  t("un-08", "Garbled but on-topic-feeling",
    "What did you have for breakfast?",
    "I had the bre... bef... brek... thing, the eg... ig... ag... in the morning.",
    { topicKeywords: ["breakfast", "eggs", "toast"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "word_finding"] }),
  t("un-09", "Press of speech, low intelligibility",
    "Tell me about your family.",
    "yes the and they all of them you know with the and so on yes the family yes.",
    { topicKeywords: ["family", "kids", "wife"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "incomplete"] }),
  t("un-10", "Single nonsense utterance",
    "Tell me about your day.",
    "klenter.",
    { topicKeywords: ["day", "today"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "no_response", "incomplete"] }),
  t("un-11", "Perseveration on single word",
    "What did you do this morning?",
    "morning morning morning morning and then morning.",
    { topicKeywords: ["morning"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "incomplete"] }),
  t("un-12", "Phonemic paraphasia cluster",
    "What is your favorite food?",
    "I like the spasketti, no spagiketti, with the matebools.",
    { topicKeywords: ["food", "favorite", "pasta"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "word_finding"] }),
  t("un-13", "Speech recognition garbled output",
    "Tell me about your day.",
    "wuh wen tuh thuh nuh fer thuh tuh.",
    { topicKeywords: ["day", "today"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "no_response"] }),
  t("un-14", "Half-formed words throughout",
    "What did you do on the weekend?",
    "I wen... uh... pla... wi... mmm... thuh... fa...",
    { topicKeywords: ["weekend", "family"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "word_finding", "incomplete"] }),
  t("un-15", "Random topic switching mid-utterance",
    "Tell me about your breakfast.",
    "the eggs and then car the dog window blue Tuesday.",
    { topicKeywords: ["breakfast", "eggs", "toast"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "off_topic"] }),
  t("un-16", "Thought continuation — garbled finish",
    "When the phone rang, I quickly...",
    "blagged the rinning thing and sed hella to the prison.",
    { exerciseSlug: "thought_continuation",
      topicKeywords: ["phone", "answered", "ring"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear"] }),
  t("un-17", "Mostly fillers with one real word",
    "Tell me about your morning.",
    "uh um eh hmm um eh coffee uh um eh hmm.",
    { topicKeywords: ["morning", "coffee", "breakfast"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "word_finding", "incomplete"] }),
  t("un-18", "Rhythm preserved but content empty",
    "What did you do yesterday?",
    "well you know how it is when you have the thing and you don't.",
    { topicKeywords: ["yesterday", "did"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "off_topic", "incomplete"] }),
  t("un-19", "Sound-level distortion of correct words",
    "What did you have for breakfast?",
    "I had ekks and tose with kuffy this morling.",
    { topicKeywords: ["breakfast", "eggs", "toast", "coffee"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "fluent_correct"] }),
  t("un-20", "Single garbled syllable",
    "Tell me about your weekend.",
    "blup.",
    { topicKeywords: ["weekend"] },
    { errorType: "unclear", adaptation: "down", success: false,
      acceptableErrorTypes: ["unclear", "no_response", "incomplete"] }),

  // =====================================================================
  // PROTECTED-CATEGORY BALANCE PACK — keep classes from skewing
  // (small additions so the new dataset doesn't drown out fluent_correct
  //  and other previously-validated categories)
  // =====================================================================
  t("fc-04", "Detailed on-topic answer",
    "Tell me about your favorite holiday.",
    "I love Thanksgiving because the whole family comes over and we cook together all afternoon.",
    { topicKeywords: ["holiday", "thanksgiving", "family", "cook"] },
    { errorType: "fluent_correct", adaptation: "up", success: true }),
  t("fc-05", "Concrete naming with context",
    "What do you use to cut paper?",
    "I use scissors, the small ones in the desk drawer.",
    { topicKeywords: ["scissors", "cut", "paper"] },
    { errorType: "fluent_correct", adaptation: "up", success: true }),
  t("fc-06", "Thought continuation — clean finish",
    "When the phone rang, I quickly...",
    "answered it before it went to voicemail.",
    { exerciseSlug: "thought_continuation",
      topicKeywords: ["phone", "answered", "ring", "call"] },
    { errorType: "fluent_correct", adaptation: "up", success: true }),
  t("ot-04", "Tangential personal story",
    "What did you have for lunch?",
    "you know my neighbor across the street just got a new car and it's bright red.",
    { topicKeywords: ["lunch", "ate", "food"] },
    { errorType: "off_topic", adaptation: "down", success: false }),
  t("sr-04", "Polite refusal",
    "Tell me about your childhood.",
    "I'd rather not talk about that, can we move on please.",
    { topicKeywords: ["childhood", "memory"] },
    { errorType: "surrender", adaptation: "down", success: false,
      acceptableErrorTypes: ["surrender", "off_topic"] }),
];
